// This c++ code is generated by PictoBlox

// Included Libraries
#include <LiquidCrystal.h>

// MACROS are defined here
const int resetPin = 2;
const int enablePin = 3;
const int d4 = 8;
const int d5 = 9;
const int d6 = 10;
const int d7 = 11;
LiquidCrystal lcd16x2(resetPin, enablePin, d4, d5, d6, d7);

// Gloabl Variables are declared here
float temperatura;
float luminosidade;

// User Defined Functions
void leLuminosidade()
{
  luminosidade = analogRead(0);
}
void leTemperatura()
{
  temperatura = analogRead(1);
}
void atualizaDisplay()
{
  lcd16x2.setCursor(7 - 1, 1 - 1);
  lcd16x2.print((String(temperatura) + String(" oC")));
  lcd16x2.setCursor(6 - 1, 2 - 1);
  lcd16x2.print((String(luminosidade) + String(" Lux")));
}

void setup()
{
  // put your setup code here, to run once:
  lcd16x2.begin(16, 2);
  pinMode(0, INPUT);
  pinMode(1, INPUT);

  lcd16x2.setCursor(1 - 1, 1 - 1);
  lcd16x2.print("Ligando...");
  delay(1 * 1000);
  lcd16x2.setCursor(1 - 1, 2 - 1);
  lcd16x2.print("Ainda ligando...");
  delay(1 * 1000);
  lcd16x2.clear();
  lcd16x2.setCursor(1 - 1, 1 - 1);
  lcd16x2.print("MEDIDOR DE");
  lcd16x2.setCursor(1 - 1, 2 - 1);
  lcd16x2.print("GRANDEZAS");
  delay(1 * 1000);
  lcd16x2.clear();
  lcd16x2.setCursor(1 - 1, 1 - 1);
  lcd16x2.print("Temp: ");
  lcd16x2.setCursor(1 - 1, 2 - 1);
  lcd16x2.print("Lum: ");
  temperatura = 0;
  luminosidade = 0;
}

void loop()
{
  // put your main code here, to run repeatedly:

  leLuminosidade();
  leTemperatura();
  atualizaDisplay();
  delay(0.2 * 1000);
}
